//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seans()
        {
            this.Bilet = new HashSet<Bilet>();
        }
    
        public int id { get; set; }
        public int film_id { get; set; }
        public int salon_id { get; set; }
        public System.DateTime seans_tarihi { get; set; }
        public System.TimeSpan seans_saati { get; set; }
        public decimal ogrenci_fiyati { get; set; }
        public decimal tam_fiyat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bilet> Bilet { get; set; }
        public virtual Film Film { get; set; }
        public virtual Salon Salon { get; set; }
    }
}
